apiVersion: v1 
kind: Pod 
metadata:
 name: grafana
 namespace: default 
 labels:
  car: ferrari

spec:
  containers:
  - name: grafanacontainer
    image: wordpress:php8.2-apache
    ports:
    - containerPort: 80
