apiVersion: v1 
kind: Pod 
metadata:
 name: gettask
 namespace: default 
 labels:
  app: get

spec:
  containers:
  - name: getcontainer
    image: ashishkashyap92/gettask
    ports:
    - containerPort: 8000
    envFrom:
    - secretRef:
        name: dbdetails